name: Docker Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        tags: gitlab-mr-reviewer:test
        build-args: |
          COMMIT_SHA=${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Verify build success
      run: |
        echo "✅ Docker image built successfully!"
        echo "Image: gitlab-mr-reviewer:test"
        echo "Commit SHA: ${{ github.sha }}"
        docker images gitlab-mr-reviewer:test 